name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide detailed information below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "As a [user type], I have trouble with [problem]..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternatives you've considered
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: Who Would Benefit?
      description: Who would find this feature useful?
      multiple: true
      options:
        - Individual developers
        - Small teams (2-10)
        - Large teams (10+)
        - CI/CD automation
        - Enterprise users
        - Open source projects
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Perspective)
      description: How important is this feature to you?
      options:
        - Critical - Blocking my workflow
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Example Use Cases
      description: Provide concrete examples of how you'd use this feature
      placeholder: |
        1. When working on sprint planning...
        2. During code review...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references
      placeholder: Links to similar features in other tools, mockups, etc.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: I have reviewed the [ROADMAP](https://github.com/karolswdev/ticktr/blob/main/ROADMAP.md)
          required: true
        - label: I am willing to contribute this feature (if possible)
          required: false
